# Generated by Django 5.1.6 on 2025-03-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created_at']},
        ),
    ]
