# Generated by Django 5.1.6 on 2025-03-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course'], name='modules_course__45b24e_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_deleted'], name='modules_is_dele_c4a8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_published'], name='modules_is_publ_772fcd_idx'),
        ),
    ]
