# Generated by Django 5.1.6 on 2025-04-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'created_at'], name='Announcemen_is_acti_d47e53_idx'),
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='Announcements',
        ),
    ]
