# Generated by Django 5.1.6 on 2025-04-11 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='core_report_content_93408d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_by'], name='core_report_reporte_1c3a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_reviewed'], name='core_report_is_revi_2d0c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='core_report_created_9527e7_idx'),
        ),
        migrations.AlterModelTable(
            name='report',
            table='core_report',
        ),
    ]
