# Generated by Django 5.1.6 on 2025-03-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='assignment_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='assignment_submission',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='quiz_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='quiz_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
