# Generated by Django 5.1.6 on 2025-03-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_lessoncompletion_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncompletion',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Lesson Completion', 'verbose_name_plural': 'Lesson Completions'},
        ),
    ]
